### PR TITLE
Challenge one

### PR DESCRIPTION
**Pull request by Sonaelizebeth**

### CODE REVIEW

**Comment by abrahamparayil** [comment]
Use ` (back ticks) instead of ' (single quote) here.
<pre>
```python
# your code
```
</pre>

**Comment by abrahamparayil** [comment]
You've got the formatting right! Now your code tests whether the number is even or odd. We want to check if the number is divisible by any other number other than 1 and the number itself. You're close to the answer. Give it another go :)

**Review by AnanduR32 — CHANGES_REQUESTED** [review]
Good effort but there seems to be some issue with your logic, presently you're only checking if the input number is divisible by 2 alone, which is checking if the input number is even or odd, but you must for an input (say 18) check if 18 is divisible by 2,3,4,....,9 - only till 9 because a number is not divisible by any number larger than it's half...

To accomplish this loop through range of numbers from 2 to num//2 and check if the input number num is is divisible by any of these, if found to be divisible set flag to False and break out of loop.
Display value of flag 👍🏽

**Review by AnanduR32 — CHANGES_REQUESTED** [review]
Your code still does not function in the intended manner to find whether a number a prime or not 
Here a simple code snippet I have written:
```python
num=int(input("Enter number:"))
flag=True
if(num>1):
    for i in range(2,num//2):
        if(num%i==0):
            flag = False
            break
    print(flag)
else:
    print(False)
```
Here what I've done is taken the input as ```num``` and set flag to ```True``` then as you did in your code, performed initial check to find out whether the ```num``` is greater than 1 or not > If ```num``` greater than 1 then: 
* starts iteration of for loop from i = 2 to i = ```num``` // 2 
* for each value of i, checks if ```num```%i == 0, if ```num``` divisible by ```i``` then ```set flag = False``` and use ```break``` to come out of loop, 
* print value of ```flag``` 
* Since flag is initialized to ```True``` incase if there are no ```i``` that divides ```num``` to 0 then the value of flag never changes and the program prints the initial value of flag which is ```True``` at the end of execution of loop.

Go through the code, and update your submission. don't worry you're doing well - proceed at your own pace eventually you'll master this 😄

**Review by AfthabNihar — COMMENTED** [review]
The code now works perfectly. 
Just a side note- in the for loop,  range only needs to be till half of the input number ie, till num/2. This is because any number higher than  num/2 will not divide num except for num itself.

**Pull request merged**
