### PR TITLE
Create Sona-Elizebeth-Shaji.md

### PR DESCRIPTION
**Pull request by Sonaelizebeth**

### CODE REVIEW

**Comment by alexkjoseph** [comment]
Sorry there is no code in the file . Please update and try again
Screenshot from 2021-06-25 19-06-44

**Comment by Sonaelizebeth** [comment]
> Sorry there is no code in the file . Please update and try again
> Screenshot from 2021-06-25 19-06-44

Update Done!

**Comment by alexkjoseph** [comment]
Can you give more detailed explanation. _The explanation should always be intended for people with less programming background._
Screenshot from 2021-06-26 10-49-43

**Comment by Sonaelizebeth** [comment]
> Can you give more detailed explanation. _The explanation should always be intended for people with less programming background._
> Screenshot from 2021-06-26 10-49-43

Update Done

**Pull request merged**
