### PR TITLE
Create visakh-ts.md

### PR DESCRIPTION
**Pull request by visakh427799**
Challenge 1

### CODE REVIEW

**Comment by abrahamparayil** [comment]
There is a mistake in the program logic. The function will return `true` even for composite numbers. Feel free to add commits to fix your code!

**Comment by abrahamparayil** [comment]
```
Welcome to Node.js v12.21.0.
Type ".help" for more information.
> const isPrime = num=>{
...     let i;
...     for(i=(num-1)/2;i>1;i--){
.....         if(num%i===0)
.....             return false
.....     }
...     return true
... }
undefined
> isPrime(347)
true
> isPrime(4)
true
```

**Review by AnanduR32 — APPROVED** [review]
add `js` after the opening triple backticks to pretty print code
\```js
 const isPrime = num=>{
    let i;
     for(i=2;i<num;i++){
       if(num%i===0)
            return false
    }
  return true
 }
console.log(isPrime(4))
\```

as 
```js
 const isPrime = num=>{
    let i;
     for(i=2;i<num;i++){
       if(num%i===0)
            return false
    }
  return true
 }
console.log(isPrime(4))
```

**Review by AnanduR32 — CHANGES_REQUESTED** [review]
Code works well but for the composite number 1 it returns `true` when it's supposed to return `false` please add the appropriate program logic to handle input value `1`

**Pull request merged**
