### PR TITLE
 Leyojin_Thomas.md

### PR DESCRIPTION
**Pull request by leyojin**

### CODE REVIEW

**Review by AnanduR32 — APPROVED** [review]
Program works well but you aren't allowed to delete the template markdown file please rectify this, 
Suggest: add 'java' right after the triple backticks to pretty render the code:

\```java
import java.util.Scanner;
public class prime_number {
public static void main(String[] args) {
        ===========
          Your code here
        ===========
if(flag==0) {
System.out.println("true");
}
}
} 
}
\```

Which produces the output: 

```java
import java.util.Scanner;
public class prime_number {
public static void main(String[] args) {
int flag=0,k;
Scanner sc=new Scanner(System.in);
System.out.println("Enter the natural number\n");
int n=sc.nextInt();
if(n==1) {
System.out.println("true");
}else {
for(int i=2;i<=n/2;i++) {
k=n%i;
if(k==0) {
System.out.println("false");
flag=1; 
break;
}	
}
if(flag==0) {
System.out.println("true");
}
}
} 
}

```

**Review by AnanduR32 — CHANGES_REQUESTED** [review]
you aren't allowed to delete the template markdown file (Submission Template.md) please rectify this

**Review by AnanduR32 — COMMENTED** [review]
perfect!

**Comment by leyojin** [comment]
👍👍

**Pull request merged**
